theme: jekyll-theme-minimal
title: Intellectual Cooperation 1922-2022
Description: Centenary of the creation of the International Committee on Intellectual Cooperation of the League of Nations
markdown: kramdown
