theme: jekyll-theme-minimal
title: Caleb Abraham
logo: /images/TrutfetterPhysicsIllustration.jpeg
Description: Proof of the earths rotundity
markdown: kramdown

# Navigation
navigation:
  - title: Home page
    url: /Caleb-Abraham
  - title: CV
    url: /Caleb-Abraham/_pages/cv.md
  - title: Main research project
    url: /Caleb-Abraham/_pages/mainresearch.md
  - title: Past projects
    url: /Caleb-Abraham/_pages/pastprojects.md
  - title: SIde projects
    url: /Caleb-Abraham/_pages/sideprojects.md
  # Add other headers as needed
