theme: jekyll-theme-minimal
title: Intellectual Cooperation at the League of Nations
logo: /images/IntellectualCooperation_2022_cover.png
Description: The International Committee on Intellectual Cooperation of the League of Nations
markdown: kramdown
